//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thaicarontour2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public string Name { get; set; }
        public string Password { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string Passport { get; set; }
        public string House_number { get; set; }
        public string District { get; set; }
        public string Area { get; set; }
        public string province { get; set; }
        public string Codeid { get; set; }
        public int ID_Driver { get; set; }
    }
}
